### ISSUE TITLE
Provide more information

### ISSUE THREAD

**Issue by Pawanshr9** [isapir/Migrate2Postgres#1]
Hi,

Request you to provide more information of using this tool like
Environment Windows or Linux?
Installation and configuration steps?
some sample report which are thing i can migrate or not migrate like in ora2pg we have.
details of command which we can use for migration from MSSQL to Postgres.

Thanks
Pawan

**Comment by isapir** [comment]
These are very good questions.  I didn't get a chance to write up the documentation yet, but I filled the example config files with comments.  I published a video with a demo at https://youtu.be/5eF9_UB73TI

Let me answer these questions here for now:

>Environment Windows or Linux?
The tool is written in Java so it therefore cross-platform.  It can run on Windows, Linux, MacOS, or any platform that has a Java Runtime Environment version 1.8 or newer.

>Installation and configuration steps?
There is no real installation.  As long as you have Java 1.8 or later installed you only need to download the distribution zip archive from https://github.com/isapir/Migrate2Postgres/releases and extract it locally.

There is a sample batch script file and a sample bash script file in examples/bin, and there are sample config files in examples/conf.

The batch/bash scripts are really not required, because all they do is help build a Java command and execute it.  You can do the whole thing in the shell window without a script.  The examples show how to build the Java command easily though.

The config file is the most important one.  Each "migration project" should have its own config file.  The config files are in JSON format, and can be "standalone" where all of the configurations are in a single file, as in examples/conf/MsSqlAW2Postgres.conf, or inherit from a template where the template configurations are set first, and the config file can extend and override them, as in examples/conf/MsSqlAWT2Postgres.conf

>some sample report which are thing i can migrate or not migrate like in ora2pg we have.
The things that you can migrate are the schemas and tables, with some support for defaults.  The tables to be migrated are specified in the config file in `information_schema.query`.  See example for MSSQL at 
https://github.com/isapir/Migrate2Postgres/blob/master/src/main/resources/templates/ms-sql-server.conf#L7

Data type mapping is set in the config file in `ddl.sql_type_mapping`, see example for MSSQL at https://github.com/isapir/Migrate2Postgres/blob/master/src/main/resources/templates/ms-sql-server.conf#L61

Column defaults can be set via REGular EXpressions in `ddl.column_default_replace`, see example at https://github.com/isapir/Migrate2Postgres/blob/master/src/main/resources/templates/ms-sql-server.conf#L97

Please see the rest of the config files for more options.

>details of command which we can use for migration from MSSQL to Postgres.
The command is a standard Java command, but for users with no Java experience the batch/bash scripts can be more useful.  Please refer to them and to the Usage message, and let me know what else needs clarification at this time.

**Comment by isapir** [comment]
Added information to README.md
